- name: Show version and other user lelvel commands
  hosts: all
  gather_facts: false
  connection : network_cli
  vars:
    ansible_network_os : ios
  tasks:
    - name: run multiple command on remote nodes
      ios_command:
        commands:
          - show version
          - show ip interface brief
      register: print_output

    - debug: var=print_output.stdout_lines