---
- name: Manage GNS3 devices
  hosts: R1
  gather_facts: false
  connection: network_cli

  vars:
    cli:
      username: sultan
      password: cisco
      transport: cli
    ansible_network_os: ios

  tasks:
    - name: enable ospf
      ios_config:
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output
